import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import queryDatabase from '@/api/query-database'
import { parseProperties } from '@/utils/parse-properties'
import styled from 'styled-components'
const inter = Inter({ subsets: ['latin'] })

const { Client } = require('@notionhq/client');

const notion = new Client({ auth: process.env.NOTION_API_KEY });

const Container = styled.div`
  background-color: green;
  width: 100%;
  height: 100%;
`

export async function getStaticProps() {
  const pageDataFromNotion = await queryDatabase();
  const databaseId = 'b6c54b27d63a413390b42f41cc9e2d78';
  const databaseResponse = await notion.databases.query({
    database_id: databaseId
  });
  // console.log('data here: ', pageDataFromNotion)
  console.log('database response: ', JSON.stringify(databaseResponse))
  return {
    props: {
      pageDataFromNotion,
    },
  };
}

export default function Home(props) {
  console.log('props: ', JSON.stringify(props))
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main} style={{

        
      }} 
      >
        <Container>
          Hello, this is the page that we can work here
        </Container>
      </main>
    </>
  )
}
